# Optimization for Ultra-Fast Android Studio Build & Startup
org.gradle.jvmargs=-Xmx4096m -XX:+UseParallelGC -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true

android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
android.enableR8.fullMode=false

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
